kind: pipeline
name: on-debian
steps:
  - name: curl-install
    image: debian:jessie
    commands:
      - apt-get update && apt-get install -yq --no-install-recommends curl ca-certificates build-essential
      - cd
      - curl -L https://install.perlbrew.pl | bash
      - bash test.sh

---
kind: pipeline
name: on-centos
steps:
  - name: curl-install
    image: centos:7
    commands:
      - yum install -y perl-core.x86_64 bzip2 make
      - cd
      - curl -L https://install.perlbrew.pl | bash
      - bash test.sh
